### ISSUE TITLE
Error: Packets out of order. Got: 45 Expected: 0

### ISSUE THREAD

**Issue by KIMYUNHA9701** [yoon1000/It_so_CapstoneDesign#13]
```
var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : '101.101.165.82',
  user     : 'root',
  password : 'mysql',
  port     : 18081,
  database : 'muse'
});

connection.connect();

connection.query('SELECT * from USER', function(err, rows, fields) {
  if (!err)
    console.log('User: ', rows);
  else
    console.log('Error while performing Query.', err);
});



connection.end();
```

DB 접속이 안되는 것 같아서 확인하려고 간단하게 짜봤는데, 계속 아래와 같은 오류가 뜹니다. 어떻게 해결할 수 있을까요..? 

`Error while performing Query. { [Error: Packets out of order. Got: 45 Expected: 0] code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true }`

**Comment by headcha** [comment]
connection.query 는 비동기로 실행되기 때문에 query 문 수행이 완료 되면 callback 함수가 동작하게 되어 있어 그런데 너 코드는 query 실행하자마자 connection.end(); 로 종료 해버렸기 때문에 쿼리 수행중에 커넥션이 끊어져 버렸네 따라서 코드를 

connection.query('SELECT * from USER', function(err, rows, fields) {
  if (!err)
    console.log('User: ', rows);
  else
    console.log('Error while performing Query.', err);

 connection.end();
});

이렇게 바꿔야 할것 같다
