### ISSUE TITLE
intellij remotehost github연동

### ISSUE THREAD

**Issue by KIMYUNHA9701** [yoon1000/It_so_CapstoneDesign#16]
촤님 intellij에서 remote host(web-was)로 접속해서 코드수정하고 바로 git에 push할 수 있는 방법이 있나요? local로 하면 깃푸쉬할 수 있는 버튼이 있던데 리모트에서는 직접 터미널에 입력하는 것말고 방법을 모르겠어요! 젠킨스로 빌드 성공할 때 푸쉬하게 하려고 했는데 그것도 올바른 방법이 아닌 것 같아서 질문드려요!

**Comment by headcha** [comment]
서버에서 코드고치지말어 절대로.. 
항상로컬에서 고치고 테스트하고 푸쉬해야해

**Comment by headcha** [comment]
빌드성공하면 푸쉬가 아니라 로컬에서 테스트해보고 이상없으면 푸쉬야
