### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::9999

### ISSUE THREAD

**Issue by KIMYUNHA9701** [yoon1000/It_so_CapstoneDesign#17]
촤님 npm start하려고 하니까 계속 포트가 사용중이라고 뜨는데 어떻게 해결할 수 있을까요?
server.js PID 찾아서 kill 해도 안되고
pm2 restart를 해도 안돼서 방법을 모르겠어요!
server.js PID로 kill 하면 kill은 되는데 다시 생깁니다.

**Comment by headcha** [comment]
pm2 stop 명령어로 죽여

**Comment by KIMYUNHA9701** [comment]
stop 하고 다시 start 안해도 되는건가요?

**Comment by headcha** [comment]
다시해야지 stop 이 안된다는거야?

**Comment by KIMYUNHA9701** [comment]
아니요 pm2 stop은 되는데 pm2 stop 하고 npm start하면 서버가 잘 돌아가는데 pm2 stop 하고 pm2 start하고 npm start하면 error가 떠요 .

**Comment by headcha** [comment]
... 당연하지 pm2 start 가 npm start 와 같은거니까... 그냥 쓰지말고 pm2가 뭔지 공부해봐
