### ISSUE TITLE
젠킨스용 서버 instance 를 생성한다.

### ISSUE THREAD

**Issue by headcha** [yoon1000/It_so_CapstoneDesign#2]
[요구사항]
CI / CD 용 젠킨스 서버를 생성한다.
서버 스펙은 스탠다드 ( 2core , 50 ssd , 1~2G 메모리 ) 로 설정한다.
서버 접속 환경을 구성한다. ( ssh port , admin 계정 등 )

[완료조건]
 - 서버 접속  IP , Port , 계정 정보를 댓글로 업데이트 한다. 
 - 서버를 생성한 naver cloud 계정 ID / Pw 를 댓글로 업데이트 한다.
 - 서버 생성에 활용한 pem 파일을 업로드 한다.

**Comment by Yun9701** [comment]
촤님, 저 윤하인데 Github에 jenkins를 연결하는 실습중인데 빌드유발에서 주기를 어느정도로 설정을 하는 것이 좋을까요?

**Comment by headcha** [comment]
@Yun9701  
빌드 성격마다 다른데 일단 기본적인 빌드 주기는 개발 branch ( develop , master ) 에 push / merge 될때마다 하는게 기본이겠지?

만약 코드의 정적 결함을 분석하는 용도의 빌드라면 데일리 빌드 ( 하루 한번 ) 정도도 충분할것 같고 
배포 전 코드의 문법 결함 검증 , 배포 파일 생성 등의 목적이라면 branch 에 merge 될때마다 빌드.

이건 정답은 없으니까 다양하게 해봐. 중요한건 "왜" 그렇게 했느냐 이거니까

**Comment by headcha** [comment]
@Yun9701 
하나더 코멘트 하자면.. 지금 너가 하고 있는 연습도 일이니까 이슈 생성해서 해봐 다른 팀원들도 참고 하도록.

**Comment by Yun9701** [comment]
넵! 알겠습니다!

**Comment by Yun9701** [comment]
1. IP: 101.101.165.82
   Port: 18080
   서버이름: jenkins
2. ID: lucayang@ajou.ac.kr
   PW: Yjhjy10917!

[Jenkins.zip](https://github.com/yoon1000/It_so_CapstoneDesign/files/3782646/Jenkins.zip)

**Comment by headcha** [comment]
@KIMYUNHA9701 
이거 완료된 티켓이라면 종료해줘
