### ISSUE TITLE
젠킨스 서버에 Java 를 설치한다.

### ISSUE THREAD

**Issue by headcha** [yoon1000/It_so_CapstoneDesign#3]
[요구사항]
젠킨스는 Java Application 이다.
따라서 젠킨스를 이용하기 위해 Java 를 설치해야 한다.
Jenkins 설치 예정 버전에 따라 권장 Java 를 설치한다.

[완료조건]
- 서버에서 java --version 명령어를 입력했을때 설치된 java 버전이 노출되어야 한다.

**Comment by Yun9701** [comment]
<img width="485" alt="jenkins java 설치" src="https://user-images.githubusercontent.com/28242106/67754401-bcfa0700-fa79-11e9-99fc-5b32575f7b82.PNG">

**Comment by Yun9701** [comment]
근데 java는 저희가 설치한게 아니라 네이버 클라우드 플랫폼에서 젠킨스서버를 생성하니까 이미 설치되어있었어요.

**Comment by headcha** [comment]
난 해야할 일을 목록으로 만든거고 그 해결방안을 툴로 한거라면 너가 잘한거야

**Comment by headcha** [comment]
@KIMYUNHA9701 
종료된 티켓이면 close 해줘
