### ISSUE TITLE
Cloud DB for mysql

### ISSUE THREAD

**Issue by KIMYUNHA9701** [yoon1000/It_so_CapstoneDesign#7]
mysql 서버를 생성했다가 네이버 클라우드 플랫폼에서 제공하는 cloud DB for mysql가 DB서버를 관리하기 편하다고 해서 그 서버를 생성하기로 했습니다. 근데 cloud DB for mysql에서 DB서버 구축전에 App서버를 먼저 생성하라고 하는데 여기서의 App서버가 저희가 생성하려고 하는 WAS가 맞나요? 한시간동안 고민해봤는데 답을 모르겠어서 질문합니다.

**Comment by headcha** [comment]
맞아

**Comment by headcha** [comment]
다만 db는 직접 설치해서 쓰자

**Comment by headcha** [comment]
cloud DB for mysql 이거는 우리 취지와 좀 안맞는듯..

**Comment by KIMYUNHA9701** [comment]
네! 그럼 appserver와 dbserver를 생성하는 걸로 할게요!
